# This is a basic workflow to help you get started with Actions

name: cds-release-pipeline

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-cds-solution:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      
      # Enable long path to support long file path in CDS solutions
      - name: Support longpaths
        run: git config --system core.longpaths true
      
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run echo script
        run: echo Building Sample Solution
      
      - name: Pack Sample solution
        uses: microsoft/powerplatform-actions/pack-solution@v0
        with:
          solution-folder: Sample/Xrm.CI.Framework.Sample/Customizations/Solutions/xRMCISample/Customizations
          solution-file: out/solutions/xRMCISample.zip
          solution-type: Managed
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Solutions
          path: out/solutions/xRMCISample.zip
