# This is a basic workflow to help you get started with Actions

name: create-cds-pull-request

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  generate-pull-request:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      
      # Enable long path to support long file path in CDS solutions
      - name: Support longpaths
        run: git config --system core.longpaths true
      
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          lfs: true

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: who-am-i action
        uses: microsoft/powerplatform-actions/who-am-i@v0
        with:
          environment-url: ${{ secrets.dev_url }}
          user-name: ${{ secrets.dev_username }}
          password-secret: ${{ secrets.dev_password }}

      - name: export-solution action
        uses: microsoft/powerplatform-actions/export-solution@v0
        with:
          environment-url: ${{ secrets.dev_url }}
          user-name: ${{ secrets.dev_username }}
          password-secret: ${{ secrets.dev_password }}
          solution-name: xRMCISample
          solution-output-file: out/exported/xRMCISample.zip

      - name: unpack-solution action
        uses: microsoft/powerplatform-actions/unpack-solution@v0
        with:
          solution-file: out/exported/xRMCISample.zip
          solution-folder: out/solutions/xRMCISample
          solution-type: 'Both'
          overwrite-files: true

      - name: branch-solution, prepare it for a PullRequest
        uses: microsoft/powerplatform-actions/branch-solution@v0
        with:
          solution-folder: out/solutions/xRMCISample
          solution-target-folder: Sample/Solution
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          allow-empty-commit: true
